### ISSUE TITLE
AttributeError in logs when client drops connection

### ISSUE THREAD

**Issue by pargon-the-wise** [mrjoes/tornadio2#25]
I'm seeing this error in my logs when a client dies.

ERROR:root:Error in periodic callback
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/tornado-2.2-py2.6.egg/tornado/ioloop.py", line 479, in _run
    self.callback()
  File "/Users/progan/Projects/Workspaces/Aptana/python/cb_tornado/src/multiplexed/multiplexed.py", line 64, in broadcast_all_num
    p.send(len(cls.my_messge_buffer))
  File "build/bdist.macosx-10.6-universal/egg/tornadio2/conn.py", line 238, in send
    self.session.send_message(msg)
  File "build/bdist.macosx-10.6-universal/egg/tornadio2/session.py", line 192, in send_message
    self.flush()
  File "build/bdist.macosx-10.6-universal/egg/tornadio2/session.py", line 202, in flush
    self.handler.send_messages(self.send_queue)
  **File "build/bdist.macosx-10.6-universal/egg/tornadio2/persistent.py", line 149, in send_messages
    if self.client_terminated:
AttributeError: 'TornadioWebSocketHandler' object has no attribute 'client_terminated'**

**Comment by mrjoes** [comment]
Will take a look - tornado 2.2 changed websocket implementation slightly.
