### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by xyproto** [mrjoes/tornadio2#48]
Hi,

Please add support for Python3.

I tried packaging tornadio2 for Python 3, for Arch Linux, by using `2to3`. This resolved several issues, but there are a few minor issues left.

Thanks.

**Comment by n1k0** [comment]
+1

**Comment by chirimoya** [comment]
+1

**Comment by 755** [comment]
+1

**Comment by FZambia** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by palmkevin** [comment]
+1

**Comment by sivabudh** [comment]
I'm running into the same issue.

```
2016-03-20 14:37:38 [54511] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/circusweb/circushttpd.py", line 25, in <module>
    import tornadio2
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/__init__.py", line 25, in <module>
    from tornadio2.router import TornadioRouter
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/router.py", line 27, in <module>
    from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/persistent.py", line 143
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

**Comment by esxquillon** [comment]
+1

**Comment by fakepoet** [comment]
> 2016-03-20 14:37:38 [54511] [INFO] Using <class 'chaussette.backend._wsgiref.ChaussetteServer'> as a backend
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/circusweb/circushttpd.py", line 25, in <module>
    import tornadio2
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/__init__.py", line 25, in <module>
    from tornadio2.router import TornadioRouter
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/router.py", line 27, in <module>
    from tornadio2 import persistent, polling, sessioncontainer, session, proto, preflight, stats
  File "/root/.pyenv/versions/3.5.1/envs/uihdb/lib/python3.5/site-packages/tornadio2/persistent.py", line 143
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
same error

**Comment by yagggi** [comment]
same syntax error

**Comment by renweibo** [comment]
+1

**Comment by justquick** [comment]
This is going to have to happen by next month as Py2 support is going bye bye
