### ISSUE TITLE
ERROR - Error in periodic callback

### ISSUE THREAD

**Issue by chirimoya** [mrjoes/tornadio2#68]
I have some problems running tornadio2 in production. I get "Error in periodic callback".

Any ideas what the problem could be?

Many thanks for any hint!

Traceback (most recent call last):
  File "build/bdist.freebsd-9.1-RELEASE-amd64/egg/tornadio2/periodic.py", line 82, in _run
    next_call = self.callback()
  File "build/bdist.freebsd-9.1-RELEASE-amd64/egg/tornadio2/session.py", line 274, in _heartbeat
    self.send_message(proto.heartbeat())
  File "build/bdist.freebsd-9.1-RELEASE-amd64/egg/tornadio2/session.py", line 192, in send_message
    self.flush()
  File "build/bdist.freebsd-9.1-RELEASE-amd64/egg/tornadio2/session.py", line 202, in flush
    self.handler.send_messages(self.send_queue)
  File "build/bdist.freebsd-9.1-RELEASE-amd64/egg/tornadio2/persistent.py", line 160, in send_messages
    self.write_message(m)
  File "lib/python2.7/site-packages/tornado-3.0.1-py2.7.egg/tornado/websocket.py", line 164, in write_message
    self.ws_connection.write_message(message, binary=binary)
AttributeError: 'NoneType' object has no attribute 'write_message'

**Comment by mrjoes** [comment]
Looks like some incompatibility with Tornado 3.0.1. Will take a look.

**Comment by chirimoya** [comment]
What is the recommended tornado version? 

With tornado 3.0.1 on our dev box, which is a Ubuntu LTS, we have no problems. 

Could FreeBSD cause the problem?

**Comment by mrjoes** [comment]
Does it happen often or only for some clients?

Looks like bug in the tornado websocket implementation.

**Comment by chirimoya** [comment]
Yes, it happens often.
